/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, AcademicYear as PrismaAcademicYear } from "@prisma/client";

export class AcademicYearServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AcademicYearCountArgs, "select">
  ): Promise<number> {
    return this.prisma.academicYear.count(args);
  }

  async academicYears<T extends Prisma.AcademicYearFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AcademicYearFindManyArgs>
  ): Promise<PrismaAcademicYear[]> {
    return this.prisma.academicYear.findMany<Prisma.AcademicYearFindManyArgs>(
      args
    );
  }
  async academicYear<T extends Prisma.AcademicYearFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.AcademicYearFindUniqueArgs>
  ): Promise<PrismaAcademicYear | null> {
    return this.prisma.academicYear.findUnique(args);
  }
  async createAcademicYear<T extends Prisma.AcademicYearCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AcademicYearCreateArgs>
  ): Promise<PrismaAcademicYear> {
    return this.prisma.academicYear.create<T>(args);
  }
  async updateAcademicYear<T extends Prisma.AcademicYearUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AcademicYearUpdateArgs>
  ): Promise<PrismaAcademicYear> {
    return this.prisma.academicYear.update<T>(args);
  }
  async deleteAcademicYear<T extends Prisma.AcademicYearDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.AcademicYearDeleteArgs>
  ): Promise<PrismaAcademicYear> {
    return this.prisma.academicYear.delete(args);
  }
}
