/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AcademicYear } from "./AcademicYear";
import { AcademicYearCountArgs } from "./AcademicYearCountArgs";
import { AcademicYearFindManyArgs } from "./AcademicYearFindManyArgs";
import { AcademicYearFindUniqueArgs } from "./AcademicYearFindUniqueArgs";
import { DeleteAcademicYearArgs } from "./DeleteAcademicYearArgs";
import { AcademicYearService } from "../academicYear.service";
@graphql.Resolver(() => AcademicYear)
export class AcademicYearResolverBase {
  constructor(protected readonly service: AcademicYearService) {}

  async _academicYearsMeta(
    @graphql.Args() args: AcademicYearCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AcademicYear])
  async academicYears(
    @graphql.Args() args: AcademicYearFindManyArgs
  ): Promise<AcademicYear[]> {
    return this.service.academicYears(args);
  }

  @graphql.Query(() => AcademicYear, { nullable: true })
  async academicYear(
    @graphql.Args() args: AcademicYearFindUniqueArgs
  ): Promise<AcademicYear | null> {
    const result = await this.service.academicYear(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AcademicYear)
  async deleteAcademicYear(
    @graphql.Args() args: DeleteAcademicYearArgs
  ): Promise<AcademicYear | null> {
    try {
      return await this.service.deleteAcademicYear(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
